# -*- coding: utf-8 -*-
"""CALACULATOR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/sathyapriya2501/CODSOFT/blob/main/CALACULATOR.ipynb
"""

# Prompt the user for input
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
operation = input("Enter the operation (+, -, *, /): ")

# Function to perform arithmetic operations
def calculate(num1, num2, operation):
    if operation == '+':
        return num1 + num2
    elif operation == '-':
        return num1 - num2
    elif operation == '*':
        return num1 * num2
    elif operation == '/':
        if num2 == 0:
            return "Error: Division by zero"
        else:
            return num1 / num2
    else:
        return "Error: Invalid operation"



# Calculate and display the result
result = calculate(num1, num2, operation)
print(f"Result: {result}")

